CC = gcc

all:
	$(CC) -g lab3a.c -o lab3a

tests:
	diff super.csv super_check.csv
	diff group.csv group_check.csv
	diff bitmap.csv bitmap_check.csv
	diff inode.csv inode_check.csv
	diff directory.csv directory_check.csv
	diff indirect.csv indirect_check.csv